[package]
name = "guinea-codegen"
version.workspace = true
edition.workspace = true

[dependencies]
toml.workspace = true
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full", "extra-traits"] }
i-slint-compiler.workspace = true
walkdir.workspace = true
strsim.workspace = true
guinea-core.workspace = true
heck = "0.5"
fluent-syntax.workspace = true

[lints]
workspace = true
