[package]
name = "guinea-widgets"
version.workspace = true
edition.workspace = true

[dependencies]
guinea-core.workspace = true
tracing.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
windows-reactor = { workspace = true, features = ["canvas"] }
windows-canvas = { git = "https://github.com/microsoft/windows-rs", rev = "73befe67861e0f81c35445fdede1dd7a81da1748" }

[lints]
workspace = true
