[package]
name = "bench-table-resize"
version = "0.1.0"
edition = "2024"

[dependencies]
guinea = { path = "../../crates/guinea", features = ["widgets"] }
guinea-core = { path = "../../crates/guinea-core" }
windows-reactor = { git = "https://github.com/Tam1SH/windows-rs", rev = "63450fc98" }
anyhow = "1.0.100"

[build-dependencies]
windows-reactor-setup = { git = "https://github.com/Tam1SH/windows-rs", rev = "63450fc98" }

[workspace]
