use proc_macro::TokenStream;
use syn::{ItemImpl, ItemTrait, parse_macro_input};

mod adapter;
mod binder_gen;
mod capability;
mod contract_macros;
mod dto;

/// Backend-agnostic marker for a `UiXxxPort` trait: registers `(trait_name,
/// msg_type_name)` in the `forsl_core::contracts` registry (via `inventory`)
/// so a test-kit can auto-generate its stub - nothing about this trait is
/// UI-backend-specific, it's `send(&self, msg)` all the way down.
#[proc_macro_attribute]
pub fn port(_attr: TokenStream, item: TokenStream) -> TokenStream {
    let trait_item = parse_macro_input!(item as ItemTrait);
    contract_macros::port_impl(trait_item)
}

/// Backend-agnostic marker for a `UiXxxBindings` trait: registers full method
/// metadata in the `forsl_core::contracts` registry and generates the
/// actor-side `<Feature>Binder`/`<Feature>PartialBinder` helpers.
#[proc_macro_attribute]
pub fn bindings(_attr: TokenStream, item: TokenStream) -> TokenStream {
    let trait_item = parse_macro_input!(item as ItemTrait);
    contract_macros::bindings_impl(trait_item)
}

/// `#[port_adapter(backend = "slint", window = AppWindow)]` - Slint-specific
/// adapter-side wrapper (upgrade-check/tracing only; ports have nothing to
/// auto-generate). `backend` makes room for a future non-Slint UI backend
/// without renaming the macro.
#[proc_macro_attribute]
pub fn port_adapter(attr: TokenStream, item: TokenStream) -> TokenStream {
    let impl_block = parse_macro_input!(item as ItemImpl);
    adapter::port_adapter_impl(attr, impl_block)
}

/// `#[bindings_adapter(backend = "slint", window = AppWindow)]` - wraps only
/// the hand-written (`#[manual]`) methods present in this impl block; the
/// rest are generated by the consuming app's own build.rs as a separate
/// `impl` block.
#[proc_macro_attribute]
pub fn bindings_adapter(attr: TokenStream, item: TokenStream) -> TokenStream {
    let impl_block = parse_macro_input!(item as ItemImpl);
    adapter::bindings_adapter_impl(attr, impl_block)
}

/// `#[capability("key")]` on a marker struct - emits a `pub const <KEY>: &str`
/// right there (no registry lookup needed for the common "I just want the
/// key string" case) plus an `inventory::submit!` registration for whoever
/// needs the *whole* list (e.g. generating `capabilities.slint`).
#[proc_macro_attribute]
pub fn capability(attr: TokenStream, item: TokenStream) -> TokenStream {
    capability::capability_impl(attr, item)
}

/// Strips helper attributes (`#[manual]`, `#[tracing(...)]`, `#[slint(...)]`)
/// from a struct/enum's fields/variants - lets a DTO type carry the same
/// helper-attribute vocabulary as ports/bindings without them leaking into
/// the final compiled item.
#[proc_macro_attribute]
pub fn slint_dto(_attr: TokenStream, item: TokenStream) -> TokenStream {
    dto::slint_dto_impl(item)
}
