//! The deep-link manifest: the external surface, written down and diffed.
//!
//! The full set of addresses is derivable from the route trees, so it should
//! not also be maintained by hand. But derivable is not the same as
//! disposable: once shipped, an address lives in shortcuts, in mails, and in
//! other programs' integrations, and what bites is not a malformed link but a
//! changed one. A generated file that is committed turns that into a line in a
//! diff.
//!
//! Generated **after** compilation rather than in a build script. A build
//! script runs before `rustc` and can only re-parse the source, which means a
//! second reading to disagree with the first; here the tree is the real one,
//! already type-checked, reached through `Route::deep_links()`.
//!
//! The shape of the check is a golden file: [`check`] renders the manifest and
//! compares it with what is committed, failing when they differ.
//!
//! ```ignore
//! #[test]
//! fn deep_links_are_what_was_shipped() {
//!     guinea::manifest::check("deeplinks.toml", "guinea-processes", &[Route::deep_links()]);
//! }
//! ```
//!
//! Set `GUINEA_BLESS=1` to rewrite it. Updating is then something a person did
//! and a reviewer can see, rather than something a build did quietly.

use std::fmt::Write as _;
use std::path::Path;

use crate::link::DeepLink;

/// The manifest as text, sorted so that only real changes show up in a diff.
///
/// `scheme` is what the installer registers with the OS. It is repeated here
/// rather than left in the application's own manifest alone, because changing
/// it breaks every address at once and that belongs in the same diff as the
/// addresses.
pub fn render(scheme: &str, trees: &[&[DeepLink]]) -> String {
    let mut links: Vec<&DeepLink> = trees.iter().flat_map(|tree| tree.iter()).collect();

    // By address, not by declaration order: moving a page inside `routes!`
    // changes nothing about what the application answers to, and should not
    // read as though it did.
    links.sort_by_key(|link| (link.path, link.tree, link.route));

    let mut out = String::new();
    out.push_str(
        "# @generated by guinea. Do not edit; run the manifest test with GUINEA_BLESS=1.\n\
         #\n\
         # Every address this application answers to. A removed line is a link\n\
         # already in the world that stopped working; an added one is a new way in\n\
         # for anything on the machine.\n\n",
    );
    let _ = writeln!(out, "scheme = {}\n", quoted(scheme));

    for link in links {
        out.push_str("[[link]]\n");
        let _ = writeln!(out, "tree = {}", quoted(link.tree));
        let _ = writeln!(out, "route = {}", quoted(link.route));
        let _ = writeln!(out, "path = {}", quoted(link.path));

        out.push_str("captures = [");
        for (at, capture) in link.captures.iter().enumerate() {
            if at > 0 {
                out.push_str(", ");
            }
            let _ = write!(
                out,
                "{{ name = {}, type = {} }}",
                quoted(capture.name),
                quoted(capture.ty)
            );
        }
        out.push_str("]\n");

        out.push_str("guards = [");
        for (at, guard) in link.guards.iter().enumerate() {
            if at > 0 {
                out.push_str(", ");
            }
            out.push_str(&quoted(guard));
        }
        out.push_str("]\n");

        let _ = writeln!(out, "restorable = {}\n", link.restorable);
    }

    out
}

fn quoted(text: &str) -> String {
    let mut out = String::with_capacity(text.len() + 2);
    out.push('"');
    for character in text.chars() {
        match character {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            other => out.push(other),
        }
    }
    out.push('"');
    out
}

/// Compares the manifest at `path` with what the trees actually declare, and
/// panics with the difference when they disagree.
///
/// Writes it instead when `GUINEA_BLESS` is set, which is also how the file is
/// created the first time.
///
/// `path` is taken relative to the crate the test belongs to - `CARGO_MANIFEST_DIR`
/// - so the file lands next to the application rather than wherever the test
/// runner happened to start.
#[track_caller]
pub fn check(path: impl AsRef<Path>, scheme: &str, trees: &[&[DeepLink]]) {
    let path = match std::env::var_os("CARGO_MANIFEST_DIR") {
        Some(root) => Path::new(&root).join(path),
        None => path.as_ref().to_path_buf(),
    };

    let rendered = render(scheme, trees);
    let committed = std::fs::read_to_string(&path).ok();

    if committed.as_deref() == Some(rendered.as_str()) {
        return;
    }

    if std::env::var_os("GUINEA_BLESS").is_some() {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).expect("creating the manifest's directory");
        }
        std::fs::write(&path, &rendered).expect("writing the manifest");
        return;
    }

    let Some(committed) = committed else {
        panic!(
            "no deep-link manifest at {}.\n\n\
             Run this test again with GUINEA_BLESS=1 to write it, then commit it: \
             from then on a change to the application's external surface arrives as \
             a diff instead of as a surprise.\n\n{rendered}",
            path.display()
        );
    };

    panic!(
        "the deep-link manifest at {} no longer matches the route trees.\n\n{}\n\n\
         Each of these is an address the application answers to, or stopped \
         answering to. Read them before running with GUINEA_BLESS=1: a line that \
         went away is a link already in the world that will stop opening, and one \
         that appeared is a new way in for anything on the machine.",
        path.display(),
        difference(&committed, &rendered)
    );
}

/// Line-wise, because that is how the file is read: every entry is one line,
/// and what a reviewer wants is which lines are new and which are gone.
fn difference(committed: &str, rendered: &str) -> String {
    let before: Vec<&str> = committed.lines().filter(|line| interesting(line)).collect();
    let after: Vec<&str> = rendered.lines().filter(|line| interesting(line)).collect();

    let mut out = String::new();
    for line in &before {
        if !after.contains(line) {
            let _ = writeln!(out, "- {line}");
        }
    }
    for line in &after {
        if !before.contains(line) {
            let _ = writeln!(out, "+ {line}");
        }
    }

    if out.is_empty() {
        // Same lines, different order or spacing - still a difference, and
        // saying "no changes" would be a lie.
        out.push_str("(the entries are the same; the file's layout is not)");
    }

    out
}

fn interesting(line: &str) -> bool {
    let line = line.trim();
    !line.is_empty() && !line.starts_with('#') && line != "[[link]]"
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::link::Capture;

    const PROCESSES: DeepLink = DeepLink {
        tree: "Route",
        route: "Processes",
        path: "/:context/processes",
        captures: &[Capture {
            name: "context",
            ty: "String",
        }],
        guards: &[],
        restorable: true,
    };

    const SECRETS: DeepLink = DeepLink {
        tree: "Route",
        route: "Secrets",
        path: "/:context/secrets",
        captures: &[Capture {
            name: "context",
            ty: "String",
        }],
        guards: &["Session"],
        restorable: false,
    };

    #[test]
    fn a_link_renders_with_everything_that_can_break_it() {
        let rendered = render("guinea-processes", &[&[PROCESSES]]);

        assert!(rendered.contains("scheme = \"guinea-processes\""));
        assert!(rendered.contains("path = \"/:context/processes\""));
        assert!(rendered.contains("{ name = \"context\", type = \"String\" }"));
        assert!(rendered.contains("restorable = true"));
    }

    #[test]
    fn declaration_order_is_not_a_change() {
        let one = render("app", &[&[PROCESSES, SECRETS]]);
        let other = render("app", &[&[SECRETS, PROCESSES]]);
        assert_eq!(one, other, "the tree was reordered, the surface was not");
    }

    #[test]
    fn a_captures_type_changing_is_a_change() {
        let widened = DeepLink {
            captures: &[Capture {
                name: "context",
                ty: "u32",
            }],
            ..PROCESSES
        };

        let difference = difference(
            &render("app", &[&[PROCESSES]]),
            &render("app", &[&[widened]]),
        );

        assert!(difference.contains("- captures = [{ name = \"context\", type = \"String\" }]"));
        assert!(difference.contains("+ captures = [{ name = \"context\", type = \"u32\" }]"));
    }

    #[test]
    fn a_guard_appearing_is_a_change() {
        let guarded = DeepLink {
            guards: &["Session"],
            ..PROCESSES
        };

        let difference = difference(&render("app", &[&[PROCESSES]]), &render("app", &[&[guarded]]));
        assert!(difference.contains("+ guards = [\"Session\"]"), "{difference}");
    }

    #[test]
    fn a_link_that_went_away_reads_as_removed() {
        let difference = difference(
            &render("app", &[&[PROCESSES, SECRETS]]),
            &render("app", &[&[PROCESSES]]),
        );

        assert!(difference.contains("- path = \"/:context/secrets\""));
        assert!(!difference.contains("- path = \"/:context/processes\""));
    }

    #[test]
    fn two_trees_are_one_surface() {
        let rendered = render(
            "app",
            &[
                &[PROCESSES],
                &[DeepLink {
                    tree: "SettingsRoute",
                    ..SECRETS
                }],
            ],
        );

        assert!(rendered.contains("tree = \"Route\""));
        assert!(rendered.contains("tree = \"SettingsRoute\""));
    }
}
