use proc_macro::TokenStream;
use syn::{ItemFn, ItemImpl, ItemTrait, parse_macro_input};

mod adapter;
mod binder_gen;
mod capability;
mod contract_macros;
mod dto;
mod feature;
mod features;
mod handler;
mod routable;

/// Backend-agnostic marker for a `UiXxxPort` trait: registers `(trait_name,
/// msg_type_name)` in the `guinea_core::contracts` registry (via `inventory`)
/// so a test-kit can auto-generate its stub - nothing about this trait is
/// UI-backend-specific, it's `send(&self, msg)` all the way down.
#[proc_macro_attribute]
pub fn port(_attr: TokenStream, item: TokenStream) -> TokenStream {
    let trait_item = parse_macro_input!(item as ItemTrait);
    contract_macros::port_impl(trait_item)
}

/// Backend-agnostic marker for a `UiXxxBindings` trait: registers full method
/// metadata in the `guinea_core::contracts` registry and generates the
/// actor-side `<Feature>Binder`/`<Feature>PartialBinder` helpers.
#[proc_macro_attribute]
pub fn bindings(_attr: TokenStream, item: TokenStream) -> TokenStream {
    let trait_item = parse_macro_input!(item as ItemTrait);
    contract_macros::bindings_impl(trait_item)
}

/// `#[port_adapter(backend = "slint", window = AppWindow)]` - Slint-specific
/// adapter-side wrapper (upgrade-check/tracing only; ports have nothing to
/// auto-generate). `backend` makes room for a future non-Slint UI backend
/// without renaming the macro.
#[proc_macro_attribute]
pub fn port_adapter(attr: TokenStream, item: TokenStream) -> TokenStream {
    let impl_block = parse_macro_input!(item as ItemImpl);
    adapter::port_adapter_impl(attr, impl_block)
}

/// `#[bindings_adapter(backend = "slint", window = AppWindow)]` - wraps only
/// the hand-written (`#[manual]`) methods present in this impl block; the
/// rest are generated by the consuming app's own build.rs as a separate
/// `impl` block.
#[proc_macro_attribute]
pub fn bindings_adapter(attr: TokenStream, item: TokenStream) -> TokenStream {
    let impl_block = parse_macro_input!(item as ItemImpl);
    adapter::bindings_adapter_impl(attr, impl_block)
}

/// `#[capability("key")]` on a marker struct - emits a `pub const <KEY>: &str`
/// right there (no registry lookup needed for the common "I just want the
/// key string" case) plus an `inventory::submit!` registration for whoever
/// needs the *whole* list (e.g. generating `capabilities.slint`).
#[proc_macro_attribute]
pub fn capability(attr: TokenStream, item: TokenStream) -> TokenStream {
    capability::capability_impl(attr, item)
}

/// Strips helper attributes (`#[manual]`, `#[tracing(...)]`, `#[slint(...)]`)
/// from a struct/enum's fields/variants - lets a DTO type carry the same
/// helper-attribute vocabulary as ports/bindings without them leaking into
/// the final compiled item.
#[proc_macro_attribute]
pub fn slint_dto(_attr: TokenStream, item: TokenStream) -> TokenStream {
    dto::slint_dto_impl(item)
}

/// Turns a plain `fn(ctx: &mut WindowFeatureInitContext<TWindow>, ...ports)`
/// into a `WindowFeature<TWindow>` struct - one closure-producing field per
/// port argument, wired up in `install`.
#[proc_macro_attribute]
pub fn window_feature(args: TokenStream, input: TokenStream) -> TokenStream {
    features::window_feature_impl(args, input)
}

/// Turns a plain `fn(ctx: &mut AppFeatureInitContext, params?)` into an
/// `AppFeature` struct.
#[proc_macro_attribute]
pub fn app_feature(args: TokenStream, input: TokenStream) -> TokenStream {
    features::app_feature_impl(args, input)
}

/// `#[route_feature(MarkerType)]` on `fn(ctx: FeatureInitContext, uri:
/// &AppUri) -> anyhow::Result<()>` - implements `RouteFeature` for the named
/// (already-declared) marker type. Never async - see `features::route_feature_impl`.
#[proc_macro_attribute]
pub fn route_feature(args: TokenStream, input: TokenStream) -> TokenStream {
    features::route_feature_impl(args, input)
}

/// `#[derive(Routable)]` on an enum whose variants carry `#[route("...")]`
/// (literal segments plus `:name` captures bound to named fields) - generates
/// `path(&self) -> String` and `parse(path: &str) -> Option<Self>`, so
/// `navigate(AppRoute::Processes { context })` and deep-link parsing both go
/// through the same typed value instead of a hand-maintained string match.
#[proc_macro_derive(Routable, attributes(route))]
pub fn derive_routable(input: TokenStream) -> TokenStream {
    routable::derive_routable_impl(input)
}

/// `#[feature_bindings]` on `impl FeatureBindings for <Name>Feature {}` -
/// fills in `type Bindings` for you (derived from the marker's own name,
/// `<Name>Feature` -> `<Name>Bindings`, matching
/// `generate_feature_bindings_adapter`'s naming convention), so nothing has
/// to name the codegen-produced storage struct itself. Separate from
/// `FeatureState` entirely - a feature with no dispatch never writes this
/// impl at all. (Not named `#[feature]` - that collides with Rust's own
/// built-in `#![feature(...)]` nightly-gate attribute.)
#[proc_macro_attribute]
pub fn feature_bindings(_attr: TokenStream, input: TokenStream) -> TokenStream {
    feature::feature_impl(input)
}

/// Turns a standalone `fn(actor: &mut A, msg: M, [ctx])` or
/// `async fn(ctx: AsyncContext<A>, msg: M)` into a real
/// `guinea_core::actor::Handler<M> for A` impl.
#[proc_macro_attribute]
pub fn handler(_attr: TokenStream, item: TokenStream) -> TokenStream {
    let input = parse_macro_input!(item as ItemFn);
    handler::generate_standalone_handler(input)
}
