[package]
name = "guinea-core"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
arc-swap.workspace = true
guinea-trace.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
derive_more = { version = "2.1.1", features = ["deref", "display", "from"] }
http = "1.3"
inventory.workspace = true
once_cell = "1.21.3"
parking_lot = "0.12.5"

[dev-dependencies]
guinea-macros.workspace = true
tokio = { workspace = true, features = ["test-util"] }

[features]
test-utils = []



