import { ScrollView, HorizontalBox, VerticalBox } from "std-widgets.slint";

export global ServicesModel {
    in property <[string]> items;
}

export component Services {
    ScrollView {
        VerticalBox {
            alignment: start;
            for item in ServicesModel.items: HorizontalBox {
                Text {
                    text: item;
                    vertical-alignment: center;
                }
            }
        }
    }
}
