//! Writing the declared route tree out in both languages.

use std::collections::HashMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use guinea_route_dsl::{Node, RouteTree, type_ident};

use crate::scan::Component;

#[derive(Debug)]
pub(crate) struct Generated {
    /// The enum, alone in its own file: a layout that switches on the route
    /// imports it, and the tree imports the layout. In one file that is a
    /// cycle, and Slint refuses it.
    pub ids: String,
    pub slint: String,
    pub rust: String,
}

/// The property the generated component switches on, and the enum it holds.
///
/// A route is a name, not a number: an index would put the generated order
/// into hand-written markup, where nothing would notice when it changed.
const PROPERTY: &str = "route";
const ENUM: &str = "RouteId";

pub(crate) fn emit(
    routes: &RouteTree,
    components: &HashMap<String, Component>,
) -> anyhow::Result<Generated> {
    let mut body = String::new();
    let mut used = Vec::new();
    let mut pages = Vec::new();

    emit_nodes(
        &routes.nodes,
        components,
        &mut Emitter {
            used: &mut used,
            pages: &mut pages,
        },
        3,
        &mut body,
    )?;

    Ok(Generated {
        ids: ids_module(&pages),
        slint: slint_module(&used, &body),
        rust: rust_module(&routes.name.to_string(), &pages),
    })
}

/// What the walk collects on its way: the components to import, and the pages
/// in declaration order.
struct Emitter<'a> {
    used: &'a mut Vec<(String, PathBuf)>,
    pages: &'a mut Vec<String>,
}

fn emit_nodes(
    nodes: &[Node],
    components: &HashMap<String, Component>,
    at: &mut Emitter,
    indent: usize,
    out: &mut String,
) -> anyhow::Result<Vec<String>> {
    let mut here = Vec::new();

    for node in nodes {
        match node {
            Node::Page { ty, .. } => {
                let (name, _) = component(ty, components, at)?;
                at.pages.push(name.clone());

                writeln!(
                    out,
                    "{:indent$}if {}: {name} {{ }}",
                    "",
                    is(std::slice::from_ref(&name)),
                    indent = indent * 4
                )?;
                here.push(name);
            }

            Node::Layout { ty, children, .. } => {
                let (name, takes_route) = component(ty, components, at)?;

                let mut inner = String::new();
                if takes_route {
                    writeln!(
                        inner,
                        "{:indent$}{PROPERTY}: root.{PROPERTY};",
                        "",
                        indent = (indent + 1) * 4
                    )?;
                }
                let below = emit_nodes(children, components, at, indent + 1, &mut inner)?;

                // A layout is only alive while one of its pages is: the branch
                // holds the pages, and Slint builds and drops it as a whole.
                writeln!(
                    out,
                    "{:indent$}if {}: {name} {{",
                    "",
                    is(&below),
                    indent = indent * 4
                )?;
                out.push_str(&inner);
                writeln!(out, "{:indent$}}}", "", indent = indent * 4)?;

                here.extend(below);
            }
        }
    }

    Ok(here)
}

/// The condition selecting one branch: `root.route == RouteId.Processes`, or a
/// choice of them.
fn is(pages: &[String]) -> String {
    let tests: Vec<String> = pages
        .iter()
        .map(|page| format!("root.{PROPERTY} == {ENUM}.{page}"))
        .collect();

    match tests.len() {
        1 => tests[0].clone(),
        _ => format!("({})", tests.join(" || ")),
    }
}

fn component(
    ty: &syn::Type,
    components: &HashMap<String, Component>,
    at: &mut Emitter,
) -> anyhow::Result<(String, bool)> {
    let name = type_ident(ty).to_string();
    let found = components.get(&name).ok_or_else(|| {
        anyhow::anyhow!(
            "no .slint under the source root exports a component named `{name}` - \
             the route tree names it, so some file has to draw it"
        )
    })?;

    if !at.used.iter().any(|(seen, _)| seen == &name) {
        at.used.push((name.clone(), found.file.clone()));
    }

    Ok((name, found.takes_route))
}

fn ids_module(pages: &[String]) -> String {
    format!(
        "// Generated by guinea-slint-build from the routes! declaration.\n\
         // One name per page, for whoever switches on the route.\n\n\
         export enum {ENUM} {{ {} }}\n",
        pages.join(", ")
    )
}

fn slint_module(used: &[(String, PathBuf)], body: &str) -> String {
    let mut out = format!(
        "// Generated by guinea-slint-build from the routes! declaration.\n\
         // The route tree, with every page in it; `route` picks the branch.\n\n\
         import {{ {ENUM} }} from \"{}\";\n",
        crate::IDS
    );

    for (name, path) in used {
        let _ = writeln!(out, "import {{ {name} }} from \"{}\";", slint_path(path));
    }

    let _ = write!(
        out,
        "\nexport component RouteTree {{\n    in property <{ENUM}> {PROPERTY};\n\n    VerticalLayout {{\n{body}    }}\n}}\n"
    );

    out
}

/// Slint reads an import as a path, and a Windows one has to be written the
/// way every other path in the file is.
fn slint_path(path: &Path) -> String {
    path.display().to_string().replace('\\', "/")
}

fn rust_module(route: &str, pages: &[String]) -> String {
    let mut arms = String::new();
    for page in pages {
        let _ = writeln!(arms, "        {route}::{page} {{ .. }} => {ENUM}::{page},");
    }

    format!(
        "// Generated by guinea-slint-build from the routes! declaration.\n\
         // Which branch of the generated tree a route shows. `{ENUM}` comes from\n\
         // the generated `.slint`, so it has to be in scope where this is included.\n\
         pub fn route_id(route: &{route}) -> {ENUM} {{\n    match route {{\n{arms}    }}\n}}\n"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn components() -> HashMap<String, Component> {
        [
            ("TabsLayout", true),
            ("Processes", false),
            ("Services", false),
            ("Metrics", false),
        ]
        .into_iter()
        .map(|(name, takes_route)| {
            (
                name.to_string(),
                Component {
                    file: PathBuf::from(format!("/ui/{name}.slint")),
                    takes_route,
                },
            )
        })
        .collect()
    }

    fn tree() -> RouteTree {
        guinea_route_dsl::find_in_source(
            r#"
            routes! {
                Route {
                    layout(TabsLayout) {
                        page(Processes, "/:context/processes") { context: String }
                        page(Services, "/:context/services") { context: String }
                    }
                    page(Metrics, "/metrics")
                }
            }
        "#,
        )
        .expect("a route tree")
    }

    #[test]
    fn a_layout_lives_while_any_of_its_pages_does() {
        let generated = emit(&tree(), &components()).expect("emit");

        assert!(
            generated.slint.contains(
                "if (root.route == RouteId.Processes || root.route == RouteId.Services): TabsLayout {"
            ),
            "got:\n{}",
            generated.slint
        );
        assert!(
            generated
                .slint
                .contains("if root.route == RouteId.Processes: Processes { }")
        );
    }

    #[test]
    fn a_layout_that_asks_for_the_route_is_handed_it() {
        let generated = emit(&tree(), &components()).expect("emit");
        assert!(
            generated.slint.contains("route: root.route;"),
            "got:\n{}",
            generated.slint
        );
    }

    #[test]
    fn a_layout_that_does_not_ask_is_left_alone() {
        let mut silent = components();
        silent.get_mut("TabsLayout").unwrap().takes_route = false;

        let generated = emit(&tree(), &silent).expect("emit");
        assert!(!generated.slint.contains("route: root.route;"));
    }

    #[test]
    fn a_page_outside_a_layout_stands_on_its_own() {
        let generated = emit(&tree(), &components()).expect("emit");
        assert!(
            generated
                .slint
                .contains("if root.route == RouteId.Metrics: Metrics { }")
        );
    }

    #[test]
    fn every_page_becomes_one_name_in_the_enum() {
        let generated = emit(&tree(), &components()).expect("emit");
        assert!(
            generated
                .ids
                .contains("export enum RouteId { Processes, Services, Metrics }"),
            "got:\n{}",
            generated.ids
        );
    }

    #[test]
    fn the_tree_imports_the_enum_rather_than_declaring_it() {
        // A layout switching on the route imports the enum, and the tree
        // imports the layout: in one file that is a cycle.
        let generated = emit(&tree(), &components()).expect("emit");

        assert!(generated.slint.contains("import { RouteId } from \"route-id.slint\";"));
        assert!(!generated.slint.contains("export enum"));
    }

    #[test]
    fn every_component_is_imported_once_from_where_it_was_found() {
        let generated = emit(&tree(), &components()).expect("emit");

        assert_eq!(
            generated.slint.matches("import { TabsLayout }").count(),
            1,
            "a layout wrapping two pages is still one import"
        );
        assert!(
            generated
                .slint
                .contains("import { Processes } from \"/ui/Processes.slint\";")
        );
    }

    #[test]
    fn the_rust_side_names_the_same_branches() {
        let generated = emit(&tree(), &components()).expect("emit");

        assert!(
            generated
                .rust
                .contains("Route::Processes { .. } => RouteId::Processes,")
        );
        assert!(
            generated
                .rust
                .contains("Route::Metrics { .. } => RouteId::Metrics,")
        );
    }

    #[test]
    fn a_page_no_file_draws_is_an_error_that_says_so() {
        let mut missing = components();
        missing.remove("Metrics");

        let error = emit(&tree(), &missing).expect_err("no component for Metrics");
        assert!(error.to_string().contains("`Metrics`"), "got: {error}");
    }
}
