[package]
name = "guinea-processes-app-example"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
guinea = { path = "../../crates/guinea", features = ["widgets"] }
guinea-core = { path = "../../crates/guinea-core" }
guinea-macros = { path = "../../crates/guinea-macros" }
amethystate = "0.9.2"
anyhow = "1.0"
inventory = "0.3"
fluent-templates = "0.14.0"
fluent-bundle = "0.16.0"
unic-langid = { version = "0.9.6", features = ["macros"] }
tokio = { version = "1", features = ["time", "rt-multi-thread"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
windows-reactor = { git = "https://github.com/Tam1SH/windows-rs", rev = "a4b40ee584a659a57fa50f163ccb7d9ff74e39c5" }
windows-canvas = { git = "https://github.com/Tam1SH/windows-rs", rev = "a4b40ee584a659a57fa50f163ccb7d9ff74e39c5" }

[build-dependencies]
windows-reactor-setup = { git = "https://github.com/Tam1SH/windows-rs", rev = "a4b40ee584a659a57fa50f163ccb7d9ff74e39c5" }
guinea-codegen = { path = "../../crates/guinea-codegen" }
