//! Getting work back onto the UI thread.
//!
//! Reactor used to hand this over as `WinUIDispatcher::for_current_thread()`.
//! It does not any more, and the replacement is not a gap in Reactor - the
//! queue was never Reactor's to lend. WinUI's `Application` establishes it for
//! the thread, Reactor never creates a controller and never shuts one down,
//! and its own background path does exactly what is below: take the queue on
//! the UI thread, keep it, and enqueue from anywhere.
//!
//! What Reactor does not hand over is the *type*. It is
//! `Microsoft.UI.Dispatching.DispatcherQueue` - the lifted one, a different
//! runtime class from `Windows.System.DispatcherQueue`, and the `windows`
//! crate carries no `Microsoft` namespace at all. So the four items this needs
//! are generated from `Microsoft.UI.winmd` and committed in
//! [`bindings`](self::bindings), rather than regenerated by a build script
//! against a 287 KB metadata file vendored beside it.
//!
//! Regenerate with `windows-bindgen` when the reactor pin moves, filtering to:
//! `DispatcherQueue.GetForCurrentThread`, `DispatcherQueueHandler`,
//! `DispatcherQueuePriority`, `IDispatcherQueue.TryEnqueueWithPriority`.

#[allow(
    nonstandard_style,
    clippy::all,
    missing_docs,
    unsafe_op_in_unsafe_fn
)]
pub(crate) mod bindings;

use std::cell::Cell;

use guinea_core::actor::{UiDispatcher, UiTask, set_ui_dispatcher};

use bindings::{DispatcherQueue, DispatcherQueueHandler, DispatcherQueuePriority};

/// The thread's queue, held for the life of the process.
///
/// `Send + Sync` because the runtime class is agile - the metadata says so and
/// the generated binding carries it through. That is what makes this usable as
/// a destination: an actor on any thread hands work to the one thread that
/// draws.
struct Queue(DispatcherQueue);

impl UiDispatcher for Queue {
    fn init(&self) {}

    fn dispatch(&self, task: UiTask) {
        // `Cell<Option<..>>` because the delegate is `Fn`, not `FnOnce`: the
        // queue could in principle invoke it more than once, and a task that
        // ran twice would be worse than one that did not run at all.
        let once = Cell::new(Some(task));
        let handler = DispatcherQueueHandler::new(move || {
            if let Some(task) = once.take() {
                task();
            }
        });

        match self
            .0
            .TryEnqueueWithPriority(DispatcherQueuePriority::Normal, &handler)
        {
            Ok(true) => {}
            // The queue refuses once it has been shut down, which is what
            // closing the last window does. Work arriving after that has
            // nowhere to run and nothing to affect.
            Ok(false) => tracing::debug!("the UI thread's queue is closed; work dropped"),
            Err(error) => tracing::warn!(%error, "the UI thread's queue refused work"),
        }
    }
}

/// Routes background work back onto the UI thread.
///
/// Must run on that thread, and after WinUI has established its queue - which
/// means from inside a component's `create`, not before `App::run_*`.
pub(crate) fn install() {
    static INIT: std::sync::Once = std::sync::Once::new();
    INIT.call_once(|| {
        let queue = DispatcherQueue::GetForCurrentThread()
            .expect("guinea's root component runs on the UI thread, which has a dispatcher queue");
        set_ui_dispatcher(Queue(queue));
    });
}
